version: 0.2

phases:
  install:
    runtime-versions:
      nodejs: 14
    commands:
      - echo Installing source NPM dependencies...
      - npm install
  pre_build:
    commands:
      - echo Build started on `date`
  build:
    commands:
      - echo Building the Vue.js app...
      - npm run build
  post_build:
    commands:
      - echo Build completed on `date`
      - echo Uploading build artifacts to S3 Bucket...
artifacts:
  files:
    - '**/*'
  base-directory: 'dist'
  discard-paths: yes
